blank_issues_enabled: true
contact_links:
  - name: Support, Help, Questions, Chat
    url: "https://openwallet.foundation/participate/"
    about: "Use the communication resources to get Help and Chat with other users"
